import { ISO_RULE, byMonthRule, byYearRule, dayMonthRule, dayOfMonthRule, relativeFutureRules, relativePastRules, slashRule, weekdayRule } from '../dateRules';
import { makeNumberWords } from '../numbers';
import type { LanguagePack } from '../types';

const MONTHS = { names: { enero: 0, ene: 0, febrero: 1, feb: 1, marzo: 2, mar: 2, abril: 3, abr: 3, mayo: 4, may: 4, junio: 5, jun: 5, julio: 6, jul: 6, agosto: 7, ago: 7, septiembre: 8, setiembre: 8, sept: 8, sep: 8, set: 8, octubre: 9, oct: 9, noviembre: 10, nov: 10, diciembre: 11, dic: 11 } };
const WEEKDAYS = { names: { domingo: 0, lunes: 1, martes: 2, miércoles: 3, miercoles: 3, jueves: 4, viernes: 5, sábado: 6, sabado: 6 }, lastAfter: ['pasado'], prefixes: ['el', 'este'] };

const numberWords = makeNumberWords({
  units: { cero: 0, uno: 1, una: 1, dos: 2, tres: 3, cuatro: 4, cinco: 5, seis: 6, siete: 7, ocho: 8, nueve: 9, diez: 10, once: 11, doce: 12, trece: 13, catorce: 14, quince: 15, dieciséis: 16, dieciseis: 16, diecisiete: 17, dieciocho: 18, diecinueve: 19, veintiuno: 21, veintiún: 21, veintiun: 21, veintidós: 22, veintidos: 22, veintitrés: 23, veintitres: 23, veinticuatro: 24, veinticinco: 25, veintiséis: 26, veintiseis: 26, veintisiete: 27, veintiocho: 28, veintinueve: 29 },
  tens: { veinte: 20, treinta: 30, cuarenta: 40, cincuenta: 50, sesenta: 60, setenta: 70, ochenta: 80, noventa: 90 },
  hundred: ['cien', 'ciento'],
  hundreds: { doscientos: 200, doscientas: 200, trescientos: 300, trescientas: 300, cuatrocientos: 400, cuatrocientas: 400, quinientos: 500, quinientas: 500, seiscientos: 600, seiscientas: 600, setecientos: 700, setecientas: 700, ochocientos: 800, ochocientas: 800, novecientos: 900, novecientas: 900 },
  thousand: ['mil'],
  million: ['millón', 'millon', 'millones'],
  connectors: ['y'],
  one: ['un', 'una'],
});

export const es: LanguagePack = {
  code: 'es',
  speechTag: 'es-ES',
  tokenizer: 'space',
  decimalComma: true,
  numberWords,
  currencyMarkers: /\$|€|euros?|dólares?|dolares?|pesos?|soles?|bolívares?|pavos|lucas|usd|eur|mxn|ars|cop|clp|pen/i,
  currencyWords: /(?<![\p{L}])(?:euros?|dólares?|dolares?|pesos?|soles?|bolívares?|pavos|lucas|usd|eur|mxn|ars|cop|clp|pen|céntimos?|centavos?)(?![\p{L}])/giu,
  incomeVerbs: ['cobré', 'cobre', 'cobrado', 'me pagaron', 'me pagó', 'me pago', 'me han pagado', 'recibí', 'recibi', 'recibido', 'gané', 'gane', 'ganado', 'ingreso', 'ingresé', 'ingrese', 'ingresaron', 'nómina', 'nomina', 'sueldo', 'salario', 'reembolso', 'reembolsaron', 'me devolvieron', 'devolución', 'devolucion', 'bono', 'bonus', 'comisión', 'comision', 'vendí', 'vendi', 'propinas', 'propina', 'regalo de', 'me dio', 'me dieron', 'me regaló', 'me regalaron', 'me transfirió', 'me transfirieron', 'depositaron', 'me depositaron', 'paga', 'pensión', 'pension', 'beca', 'intereses ganados', 'dividendos', 'premio'],
  expenseVerbs: ['gasté', 'gaste', 'gastado', 'gasto', 'pagué', 'pague', 'pagado', 'pago', 'compré', 'compre', 'comprado', 'compra', 'costó', 'costo', 'cuesta', 'me cobraron', 'pedí', 'pedi', 'cené', 'cene', 'comí', 'comi', 'cargo', 'doné', 'done', 'presté', 'preste', 'retiré', 'retire', 'envié', 'envie', 'transferí', 'transferi', 'fui a', 'tomé', 'tome', 'me gasté', 'me gaste', 'factura', 'recibo', 'abonado', 'aboné'],
  keywords: {
    salary: ['nómina', 'nomina', 'sueldo', 'salario', 'paga', 'quincena', 'cobré el sueldo', 'me pagaron el sueldo', 'depósito de nómina'],
    freelance: ['freelance', 'autónomo', 'autonomo', 'cliente', 'factura cobrada', 'trabajo extra', 'chamba', 'encargo', 'comisión', 'comision', 'consultoría', 'clases particulares', 'vendí', 'vendi', 'venta', 'propinas', 'propina', 'upwork', 'fiverr', 'wallapop'],
    gift_income: ['regalo de', 'me regaló', 'me regalaron', 'me dio', 'me dieron', 'dinero de cumpleaños', 'de mi madre', 'de mi padre', 'de mamá', 'de papá', 'de la abuela', 'del abuelo', 'aguinaldo'],
    other_income: ['reembolso', 'devolución', 'devolucion', 'me devolvieron', 'cashback', 'intereses', 'dividendos', 'bono', 'bonus', 'declaración de la renta', 'hacienda me devolvió', 'premio', 'lotería', 'loteria', 'pensión', 'pension', 'beca', 'subsidio', 'paro', 'ayuda', 'me pagó lo que le presté', 'me devolvió', 'bizum de', 'transferencia de'],
    groceries: ['supermercado', 'súper', 'super', 'mercado', 'compra de la semana', 'compra del súper', 'verduras', 'verdura', 'frutas', 'fruta', 'carne', 'pan', 'leche', 'huevos', 'mercadona', 'carrefour', 'lidl', 'aldi', 'dia', 'alcampo', 'eroski', 'walmart', 'soriana', 'chedraui', 'jumbo', 'líder', 'lider', 'éxito', 'exito', 'coto', 'carnicería', 'carniceria', 'panadería', 'panaderia', 'frutería', 'fruteria', 'pescadería', 'despensa', 'alimentos', 'víveres', 'viveres'],
    dining: ['almuerzo', 'comida', 'cena', 'desayuno', 'merienda', 'brunch', 'café', 'cafe', 'cafetería', 'cafeteria', 'restaurante', 'restaurant', 'resto', 'bar', 'cerveza', 'cervezas', 'cañas', 'vino', 'copas', 'tapas', 'pizza', 'hamburguesa', 'tacos', 'sushi', 'bocadillo', 'bocata', 'comer fuera', 'pedido', 'rappi', 'glovo', 'uber eats', 'didi food', 'pedidosya', 'just eat', 'starbucks', 'mcdonalds', "mcdonald's", 'burger king', 'helado', 'postre', 'churros', 'kebab', 'menú del día', 'menu del dia', 'comida a domicilio', 'domicilio', 'tapeo', 'aperitivo', 'refresco', 'bebida', 'bebidas'],
    rent: ['alquiler', 'renta', 'hipoteca', 'arriendo', 'casero', 'piso', 'departamento', 'comunidad', 'seguro de hogar', 'fianza', 'expensas'],
    utilities: ['luz', 'electricidad', 'factura de la luz', 'agua', 'factura del agua', 'gas', 'factura del gas', 'internet', 'wifi', 'fibra', 'teléfono', 'telefono', 'móvil', 'movil', 'celular', 'factura', 'recibo', 'calefacción', 'calefaccion', 'movistar', 'vodafone', 'orange', 'telcel', 'claro', 'cable', 'servicios', 'basura'],
    transport: ['gasolina', 'nafta', 'bencina', 'combustible', 'diésel', 'diesel', 'uber', 'cabify', 'didi', 'taxi', 'tren', 'metro', 'autobús', 'autobus', 'bus', 'colectivo', 'camión', 'micro', 'transporte', 'peaje', 'estacionamiento', 'aparcamiento', 'parking', 'coche', 'carro', 'auto', 'seguro del coche', 'seguro del auto', 'taller', 'mecánico', 'mecanico', 'neumáticos', 'llantas', 'vuelo', 'avión', 'avion', 'billete', 'boleto', 'pasaje', 'bici', 'bicicleta', 'patinete', 'renfe', 'ave', 'bonobús', 'abono transporte', 'tarjeta de transporte', 'itv', 'lavado del coche', 'alquiler de coche', 'lavado'],
    health: ['médico', 'medico', 'doctor', 'doctora', 'dentista', 'farmacia', 'medicina', 'medicinas', 'medicamentos', 'medicamento', 'hospital', 'clínica', 'clinica', 'consulta', 'seguro médico', 'seguro medico', 'terapia', 'psicólogo', 'psicologo', 'gimnasio', 'gym', 'yoga', 'pilates', 'vitaminas', 'gafas', 'lentes', 'óptica', 'optica', 'veterinario', 'masaje', 'salud', 'fisio', 'fisioterapia', 'análisis', 'analisis', 'copago'],
    entertainment: ['cine', 'película', 'pelicula', 'concierto', 'entradas', 'entrada', 'teatro', 'juego', 'videojuego', 'videojuegos', 'steam', 'playstation', 'xbox', 'nintendo', 'bolera', 'museo', 'parque', 'parque de atracciones', 'fiesta', 'discoteca', 'karaoke', 'libro', 'libros', 'hobby', 'salida', 'ocio', 'deporte', 'partido', 'fútbol', 'futbol', 'estadio', 'escape room', 'diversión', 'diversion'],
    shopping: ['amazon', 'ropa', 'zapatos', 'zapatillas', 'tenis', 'camisa', 'camiseta', 'pantalón', 'pantalon', 'pantalones', 'vestido', 'chaqueta', 'abrigo', 'compras', 'tienda', 'centro comercial', 'ikea', 'muebles', 'decoración', 'decoracion', 'leroy merlin', 'ferretería', 'ferreteria', 'electrónica', 'electronica', 'auriculares', 'móvil nuevo', 'teléfono nuevo', 'portátil', 'portatil', 'computadora', 'ordenador', 'cargador', 'regalo', 'regalos', 'juguetes', 'juguete', 'maquillaje', 'cosméticos', 'cosmeticos', 'peluquería', 'peluqueria', 'corte de pelo', 'barbería', 'barberia', 'uñas', 'sephora', 'primark', 'zara', 'el corte inglés', 'liverpool', 'mercado libre', 'pedido online', 'papelería', 'papeleria', 'hogar', 'limpieza', 'lavandería', 'lavanderia', 'tintorería', 'tintoreria', 'flores', 'plantas', 'mascota', 'mascotas', 'perro', 'gato', 'comida de perro', 'pienso', 'niños', 'bebé', 'bebe', 'pañales', 'colegio', 'universidad', 'matrícula', 'matricula', 'curso', 'clase', 'libro de texto', 'material escolar'],
    subscriptions: ['suscripción', 'suscripcion', 'suscripciones', 'netflix', 'spotify', 'hbo', 'disney', 'disney plus', 'amazon prime', 'prime', 'apple music', 'youtube premium', 'icloud', 'google one', 'dropbox', 'chatgpt', 'claude', 'adobe', 'membresía', 'membresia', 'patreon', 'periódico', 'periodico', 'dazn', 'movistar plus', 'crunchyroll', 'twitch', 'renovación', 'renovacion', 'cuota mensual', 'plan mensual', 'plan anual', 'duolingo', 'game pass', 'ps plus'],
    debt: ['tarjeta de crédito', 'tarjeta de credito', 'tarjeta', 'préstamo', 'prestamo', 'crédito', 'credito', 'deuda', 'cuota', 'cuotas', 'pago mínimo', 'pago minimo', 'intereses', 'mora', 'plazo', 'financiación', 'financiacion', 'klarna', 'pagar la tarjeta'],
    savings: ['ahorro', 'ahorros', 'transferencia', 'fondo de emergencia', 'inversión', 'inversion', 'invertí', 'inverti', 'inversiones', 'jubilación', 'jubilacion', 'plan de pensiones', 'acciones', 'cripto', 'bitcoin', 'aparté', 'aparte', 'cuenta de ahorro', 'cuenta de ahorros', 'fondo', 'etf'],
    other_expense: ['comisión bancaria', 'comisiones', 'cajero', 'efectivo', 'retiro', 'retirada', 'donación', 'donacion', 'donativo', 'caridad', 'iglesia', 'impuestos', 'impuesto', 'hacienda', 'multa', 'correos', 'envío', 'envio', 'paquete', 'varios', 'otros', 'cosas', 'bizum', 'paypal', 'seguro', 'seguro de vida', 'guardería', 'guarderia', 'niñera', 'ninera', 'escuela', 'educación', 'educacion', 'abogado', 'gestor', 'notario', 'boda', 'vacaciones', 'viaje', 'hotel', 'airbnb', 'hostal', 'alojamiento', 'propina'],
  },
  stopwords: ['el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'de', 'del', 'en', 'a', 'al', 'por', 'para', 'con', 'sin', 'y', 'o', 'pero', 'que', 'me', 'te', 'se', 'mi', 'mis', 'tu', 'tus', 'su', 'sus', 'nuestro', 'nuestra', 'yo', 'hoy', 'ayer', 'mañana', 'noche', 'tarde', 'semana', 'mes', 'año', 'gasté', 'gaste', 'pagué', 'pague', 'compré', 'compre', 'gasto', 'pago', 'compra', 'euros', 'euro', 'dólares', 'dolares', 'pesos', 'cada', 'total', 'otra', 'vez', 'también', 'entonces', 'muy', 'nuevo', 'nueva', 'más', 'menos', 'último', 'última', 'próximo', 'próxima', 'meta', 'objetivo', 'ahorrar', 'ahorré', 'ahorro', 'añadir', 'añadí', 'puse', 'hacia', 'dentro', 'fui', 'ir', 'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez', 'entrada', 'ingreso', 'dinero', 'algo', 'cosa', 'como', 'hace', 'unos', 'he', 'ha', 'esta', 'este', 'eso'],
  pastDateRules: [
    ISO_RULE,
    ...relativePastRules({
      today: ['hoy', 'esta mañana', 'esta tarde', 'esta noche', 'hoy por la mañana', 'hoy por la tarde'],
      yesterday: ['ayer', 'anoche', 'ayer por la mañana', 'ayer por la tarde', 'ayer por la noche', 'ayer noche'],
      dayBeforeYesterday: ['anteayer', 'antier', 'antes de ayer'],
      lastWeek: ['la semana pasada', 'semana pasada'],
      lastMonth: ['el mes pasado', 'mes pasado'],
      daysAgo: /\bhace (\d+|un|una) d[ií]as?\b/,
      weeksAgo: /\bhace (\d+|una) semanas?\b/,
      monthsAgo: /\bhace (\d+|un) mes(?:es)?\b/,
      oneWords: ['un', 'una'],
    }),
    dayMonthRule(MONTHS, { pre: ['el', 'el día', 'el dia'], between: ['de'] }),
    dayOfMonthRule(/\bel d[ií]a (\d{1,2})\b/),
    weekdayRule(WEEKDAYS),
    slashRule(true),
  ],
  futureDateRules: [
    ISO_RULE,
    ...relativeFutureRules({
      endOfYear: ['a fin de año', 'a final de año', 'para fin de año', 'para final de año', 'antes de fin de año', 'antes de final de año', 'fin de año', 'final de año', 'a finales de año', 'para finales de año'],
      endOfNextYear: ['a fin del año que viene', 'para finales del año que viene', 'fin del año que viene'],
      endOfMonth: ['a fin de mes', 'para fin de mes', 'antes de fin de mes', 'fin de mes', 'final de mes', 'a finales de mes', 'para finales de mes'],
      nextYear: ['el año que viene', 'para el año que viene', 'el próximo año', 'el proximo año', 'el año próximo', 'el año proximo', 'para el próximo año', 'el año que entra'],
      nextMonth: ['el mes que viene', 'para el mes que viene', 'el próximo mes', 'el proximo mes', 'el mes próximo', 'el mes proximo', 'para el próximo mes', 'el mes que entra'],
      christmas: ['para navidad', 'antes de navidad', 'para navidades', 'navidad'],
      inDays: /\ben (\d+|un) d[ií]as?\b/,
      inWeeks: /\ben (\d+|una) semanas?\b/,
      inMonths: /\ben (\d+|un) mes(?:es)?\b/,
      inYears: /\ben (\d+|un) años?\b/,
      oneWords: ['un', 'una'],
      seasons: { spring: ['para la primavera', 'antes de la primavera', 'para primavera'], summer: ['para el verano', 'antes del verano', 'para verano', 'este verano'], fall: ['para el otoño', 'antes del otoño', 'para otoño'], winter: ['para el invierno', 'antes del invierno', 'para invierno'] },
    }),
    dayMonthRule(MONTHS, { pre: ['para el', 'antes del', 'hasta el', 'el', 'para'], between: ['de'], future: true }),
    byMonthRule(MONTHS, ['para', 'antes de', 'hasta', 'en', 'para finales de', 'a finales de']),
    byYearRule(['para', 'antes de', 'hasta', 'en']),
  ],
  goalLead: /^(?:meta|objetivo|nueva meta|nuevo objetivo|meta de ahorro|objetivo de ahorro)\s*:?\s*/,
  goalIntent: /(?<![\p{L}])(?:quiero ahorrar|me gustaría ahorrar|me gustaria ahorrar|necesito ahorrar|quiero juntar|quiero guardar|quiero reunir|tengo que ahorrar|ahorrar|juntar|reunir)(?![\p{L}])/iu,
  goalPastVerbs: /(?<![\p{L}])(?:ahorré|ahorre|aparté|aparte|puse|añadí|añadi|agregué|agregue|transferí|transferi|junté|junte|guardé|guarde|metí|meti|sumé|sume)(?![\p{L}])/iu,
  contributionVerbs: /(?<![\p{L}])(?:añad(?:í|i|ir|e|o)|agreg(?:ué|ue|ar|o|a)|pus(?:e|o)|poner|pongo|ahorr(?:é|e|o)|apart(?:é|e|o)|transfer(?:í|i)|junt(?:é|e|o)|guard(?:é|e|o)|met(?:í|i|o)|sum(?:é|e|o)|deposit(?:é|e|o))(?![\p{L}])/iu,
  contributionPreps: 'a|al|a la|para|para la|para el|hacia|en|en la|en el',
  forWords: 'para|para el|para la|para un|para una|para mi|para mis|para los|para las',
  goalWords: 'meta|objetivo',
  articles: /^(?:(?:el|la|los|las|un|una|unos|unas|mi|mis|nuestro|nuestra|nuevo|nueva)\s+)+/,
  leadingFiller: /^(?:(?:hoy|ayer|pues|bueno|también|otra|vez|gasté|gaste|pagué|pague|compré|compre|gasto|pago|compra|en|de|del|por|para|con|a|al|el|la|los|las|un|una|unos|unas|mi|mis|me|se|he|ha|fui|otro|otra|unos|casi|como|aprox|aproximadamente|más o menos|mas o menos)\s+)+/,
  trailingFiller: /(?:\s+(?:hoy|ayer|en|de|del|por|para|con|a|al|el|la|los|las|un|una|y|cada|total|otra vez|también|por favor|gracias|eso|esto|más o menos|mas o menos|aprox))+$/,
  noteStrip: [],
  contextualStrings: ['euros', 'dólares', 'pesos', 'supermercado', 'alquiler', 'nómina', 'meta', 'Netflix', 'Uber'],
};
